FROM rust:1-slim-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends \
    wrk \
    btop \
    && rm -rf /var/lib/apt/lists/*

RUN cargo install cargo-watch

WORKDIR /app

CMD ["cargo", "watch", "-x", "run"]
