services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - target:/app/target
    ports:
      - "9876:9876"
    stdin_open: true
    tty: true
    cpus: 4
    mem_limit: 4g

volumes:
  target:
